quarkus:
  #Logging
  log:
    category:
      "io.quarkus.category":
        level: INFO
  #HTTP Server
  http:
    host: 0.0.0.0
  #Datasource
  datasource:
    db-kind: postgresql
    username: quarkus
    password: quarkus
    reactive:
      url: vertx-reactive:postgresql://localhost:5432/db
    devservices:
      port: 5432
      db-name: db
      username: quarkus
      password: quarkus
      enabled: true
  #ORM
  hibernate-orm:
    database:
      generation: 
        ~: "drop-and-create"
    log:
      format-sql: true
      sql: true